name: MinigameCore
version: ${project.version}
main: com.github.haocen2004.Main
api-version: 1.13
authors: [Hao_cen]
commands:
  shuffle:
    description: none
    usage: /shuffle start/stop
  randomray:
    description: none
    usage: /randomray start/stop
  assassin:
   description: none
   usage: /assassin start/stop
  minigame:
    description: none
    usage: /minigame reload